Resource under YouTube channel added.
developer-student-clubs/dev-resources pull request #20
Opened 2021-07-01 13:04 UTC by Preetmungara

#### Changes done,
Following channel added.
- CodeNCode
- Abdul Bari
- Gaurav Sen
- Neal Wu
- Program With Erik
- Tech With Tim
- CodeWithHarry

Fix <#19>

Kindly Review.

2021-07-02 05:13 UTC, Hardik0307 requested changes

2021-07-02 05:13 UTC, Hardik0307 commented on README.md
> +| [Gaurav Sen](https://www.youtube.com/channel/UCRPMAqdtSgd0Ipeef7iFsKw) | System design video for begineer in simplest form.|
spelling error - change to "beginner"

2021-07-03 05:03 UTC, Preetmungara commented
**Typo Fixed, review again** @Hardik0307

2021-07-03 05:13 UTC, Hardik0307 approved these changes
LGTM!

2021-07-03 05:15 UTC, merged